grade_curricular = {
    'Matemática básica':{}, 
    'Construção de páginas da web':{},
    'Inglês Instrumental':{},
    'Introdução a Informática':{},
    'Projeto e Desenvolvimento de Algortimos':{},
    'Fundamentos de Algoritmos de Computação':{},
    'Organização de Computadores':{},
    'Algebra Linear':{},
    'Fundamentos de Programação':{},
    'Matemática para Computação':{},
    'Física para Computação':{},
    'Estrutura de Dados':{},
    'Programação com Interfaces Gráficas':{},
    'Probabilidade e Estatística':{},
    'Modelagem de Informação':{},
    'Sistemas Operacionais':{},
    'Banco de Dados':{},
    'Programação Orientada a Objetos':{},
    'Engenharia de Software':{},
    'Redes de Computadores I':{},
    'Análise de Sistemas':{},
    'Programação de Aplicações Web':{},
    'Empreendedorismo e Ética':{},
    'TCC':{},
    'Redes de Computadores II':{},
    'Arquitetura e Projeto de Sistemas':{},
    'Computação Gráfica':{}
}