grade_curricular = {
    'Matemática básica':{'Periodo':1,'Sigla':'MB','Horas':60,'Requisito':None}, 
    'Construção de páginas da web':{'Periodo':1,'Sigla':'CPW','Horas':40,'Requisito':None},
    'Inglês Instrumental':{'Periodo':1,'Sigla':'II','Horas':40,'Requisito':None},
    'Introdução a Informática':{'Periodo':1,'Sigla':'IAI','Horas':80,'Requisito':None},
    'Projeto e Desenvolvimento de Algortimos':{'Periodo':1,'Sigla':'PDA','Horas':80,'Requisito':None},
    'Fundamentos de Algoritmos de Computação':{'Periodo':2,'Sigla':'FAC','Horas':80,'Requisito':'MB'},
    'Organização de Computadores':{'Periodo':2,'Sigla':'ODC','Horas':80,'Requisito':'IAI'},
    'Algebra Linear':{'Periodo':2,'Sigla':'ALGLIN','Horas':80,'Requisito':None},
    'Fundamentos de Programação':{'Periodo':2,'Sigla':'FP','Horas':80,'Requisito':'PDA'},
    'Matemática para Computação':{'Periodo':3,'Sigla':'MATCOMP','Horas':80,'Requisito':'FAC'},
    'Física para Computação':{'Periodo':3,'Sigla':'FISCOMP','Horas':80,'Requisito':None},
    'Estrutura de Dados':{'Periodo':3,'Sigla':'ED','Horas':80,'Requisito':'PDA'},
    'Programação com Interfaces Gráficas':{'Periodo':3,'Sigla':'PIG','Horas':80,'Requisito':'FP'},
    'Probabilidade e Estatística':{'Periodo':4,'Sigla':'PE','Horas':80,'Requisito':'MATCOMP'},
    'Modelagem de Informação':{'Periodo':4,'Sigla':'MDI','Horas':80,'Requisito':None},
    'Sistemas Operacionais':{'Periodo':4,'Sigla':'SO','Horas':80,'Requisito':'ODC'},
    'Banco de Dados':{'Periodo':4,'Sigla':'BD','Horas':80,'Requisito':'ED'},
    'Programação Orientada a Objetos':{'Periodo':4,'Sigla':'POO','Horas':80,'Requisito':'FP'},
    'Engenharia de Software':{'Periodo':5,'Sigla':'EDS','Horas':80,'Requisito':'MDI'},
    'Redes de Computadores I':{'Periodo':5,'Sigla':'RC1','Horas':120,'Requisito':'SO, FISCOMP'},
    'Análise de Sistemas':{'Periodo':5,'Sigla':'AS','Horas':80,'Requisito':'BD'},
    'Programação de Aplicações Web':{'Periodo':5,'Sigla':'PAW','Horas':80,'Requisito':'BD, FP'},
    'Empreendedorismo e Ética':{'Periodo':6,'Sigla':'EE','Horas':80,'Requisito':None},
    'Tese de Conclusão de Curso':{'Periodo':6,'Sigla':'TCC','Horas':120,'Requisito':None},
    'Redes de Computadores II':{'Periodo':6,'Sigla':'RC2','Horas':120,'Requisito':'RC1'},
    'Arquitetura e Projeto de Sistemas':{'Periodo':6,'Sigla':'APS','Horas':80,'Requisito':'AS'},
    'Computação Gráfica':{'Periodo':6,'Sigla':'CG','Horas':80,'Requisito':'PIG, ALGLIN'}
    }

descricao_disciplina = {
    'Matemática básica':{}, 
    'Construção de páginas da web':{},
    'Inglês Instrumental':{},
    'Introdução a Informática':{},
    'Projeto e Desenvolvimento de Algortimos':{},
    'Fundamentos de Algoritmos de Computação':{},
    'Organização de Computadores':{},
    'Algebra Linear':{},
    'Fundamentos de Programação':{},
    'Matemática para Computação':{},
    'Física para Computação':{},
    'Estrutura de Dados':{},
    'Programação com Interfaces Gráficas':{},
    'Probabilidade e Estatística':{},
    'Modelagem de Informação':{},
    'Sistemas Operacionais':{},
    'Banco de Dados':{},
    'Programação Orientada a Objetos':{},
    'Engenharia de Software':{},
    'Redes de Computadores I':{},
    'Análise de Sistemas':{},
    'Programação de Aplicações Web':{},
    'Empreendedorismo e Ética':{},
    'Tese de Conclusão de Curso':{},
    'Redes de Computadores II':{},
    'Arquitetura e Projeto de Sistemas':{},
    'Computação Gráfica':{}
}