grade_curricular = {
    'Matemática básica':{'periodo':1,'sigla':'MB','horas':60,'requisito':None}, 
    'Construção de páginas da web':{'periodo':1,'sigla':'CPW','horas':40,'requisito':None},
    'Inglês Instrumental':{'periodo':1,'sigla':'II','horas':40,'requisito':None},
    'Introdução a Informática':{'periodo':1,'sigla':'IAI','horas':80,'requisito':None},
    'Projeto e Desenvolvimento de Algortimos':{'periodo':1,'sigla':'PDA','horas':80,'requisito':None},
    'Fundamentos de Algoritmos de Computação':{'periodo':2,'sigla':'FAC','horas':80,'requisito':'MB'},
    'Organização de Computadores':{'periodo':2,'sigla':'ODC','horas':80,'requisito':'IAI'},
    'Algebra Linear':{'periodo':2,'sigla':'ALGLIN','horas':80,'requisito':None},
    'Fundamentos de Programação':{'periodo':2,'sigla':'FP','horas':80,'requisito':'PDA'},
    'Matemática para Computação':{'periodo':3,'sigla':'MATCOMP','horas':80,'requisito':'FAC'},
    'Física para Computação':{'periodo':3,'sigla':'FISCOMP','horas':80,'requisito':None},
    'Estrutura de Dados':{'periodo':3,'sigla':'ED','horas':80,'requisito':'PDA'},
    'Programação com Interfaces Gráficas':{'periodo':3,'sigla':'PIG','horas':80,'requisito':'FP'},
    'Probabilidade e Estatística':{'periodo':4,'sigla':'PE','horas':80,'requisito':'MATCOMP'},
    'Modelagem de Informação':{'periodo':4,'sigla':'MDI','horas':80,'requisito':None},
    'Sistemas Operacionais':{'periodo':4,'sigla':'SO','horas':80,'requisito':'ODC'},
    'Banco de Dados':{'periodo':4,'sigla':'BD','horas':80,'requisito':'ED'},
    'Programação Orientada a Objetos':{'periodo':4,'sigla':'POO','horas':80,'requisito':'FP'},
    'Engenharia de Software':{'periodo':5,'sigla':'EDS','horas':80,'requisito':'MDI'},
    'Redes de Computadores I':{'periodo':5,'sigla':'RC1','horas':120,'requisito':'SO, FISCOMP'},
    'Análise de Sistemas':{'periodo':5,'sigla':'AS','horas':80,'requisito':'BD'},
    'Programação de Aplicações Web':{'periodo':5,'sigla':'PAW','horas':80,'requisito':'BD, FP'},
    'Empreendedorismo e Ética':{'periodo':6,'sigla':'EE','horas':80,'requisito':None},
    'Tese de Conclusão de Curso':{'periodo':6,'sigla':'TCC','horas':120,'requisito':None},
    'Redes de Computadores II':{'periodo':6,'sigla':'RC2','horas':120,'requisito':'RC1'},
    'Arquitetura e Projeto de Sistemas':{'periodo':6,'sigla':'APS','horas':80,'requisito':'AS'},
    'Computação Gráfica':{'periodo':6,'sigla':'CG','horas':80,'requisito':'PIG, ALGLIN'}
    }